version: '3.3'

services:
        bck-end:
          build: ./back-end
          ports:
            - 8080:8080
          tty: true
          stdin_open: true
          environment:
            - PROD=0
          volumes:
            - ./:/home/api/WellCheck

        dbMysql:
          image: mysql:8.0.3
          restart: always
          environment:
              MYSQL_ROOT_PASSWORD: 1q2W3e #CONFIG.DB_PASS
              MYSQL_DATABASE: wellcheck #CONFIG.DB_NAME
          volumes:
            - ./db/db_data:/var/lib/mysql
            - ./db/mysql-dump:/docker-entrypoint-initdb.d

        front-adm:
           image: adminer
           restart: always
           ports:
             - 8081:8080
           depends_on:
             - dbMysql

volumes:
  db_data:
